service: beforis

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /(.*)/
  static_files: public/\1/index.html
  upload: public/(.*)/index.html
  secure: always

- url: /(.*)
  static_files: public/\1
  upload: public/(.*)
  secure: always

error_handlers:
  - file: public/404.html
